# Render.com deployment configuration
services:
  - type: web
    name: realestate-marketplace-ui
    runtime: static
    repo: https://github.com/Akfslgn/Realestate-marketplace-ui
    envVars:
      - key: VITE_APP_NAME
        sync: false
      - key: VITE_API_PREFIX
        sync: false
      - key: VITE_BACKEND_HOST
        sync: false
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
version: "1.0.1"
